export const FINANCIAL_TIPS: { body: string; category: string }[] = [
  // saving
  { body: "Save first, spend later. Move at least 10% of any income to MTN MoMo savings the moment it arrives.", category: "saving" },
  { body: "Set a savings goal in MyTereka and automate a weekly transfer — even UGX 5,000 builds a habit.", category: "saving" },
  { body: "Keep an emergency fund of at least 3 months of expenses in a liquid account like MTN MoMo.", category: "saving" },
  { body: "Lock your savings goal in MyTereka so you can't withdraw before the target date.", category: "saving" },
  { body: "Saving UGX 2,000 daily for a year gives you over UGX 700,000 — buy a bicycle or clear school fees.", category: "saving" },
  { body: "Join a SACCO — they pay annual dividends on savings, unlike most mobile money accounts.", category: "saving" },
  { body: "After receiving salary, immediately send savings to a separate account you don't carry on your phone.", category: "saving" },
  { body: "A small amount saved consistently beats a large amount saved occasionally. Consistency is everything.", category: "saving" },
  { body: "Review your savings goals every month. Increase your contribution by UGX 1,000 each month.", category: "saving" },
  { body: "Use mobile money group savings (chamas) with trusted friends to keep each other accountable.", category: "saving" },
  { body: "Before buying anything over UGX 50,000, wait 48 hours. Impulse purchases rarely feel necessary after that.", category: "saving" },
  { body: "Airtel Money and MTN MoMo both earn no interest — move long-term savings to a SACCO or bank.", category: "saving" },
  { body: "The best time to start saving was yesterday. The second best time is today.", category: "saving" },
  { body: "Name your savings goal — 'Kampala Land 2027' feels more real than 'savings account'.", category: "saving" },
  { body: "Windfall money (bonus, gift, refund) — save 50% before spending any of it.", category: "saving" },
  { body: "Every time you skip a chapati or soda, add that money to savings. Small swaps add up.", category: "saving" },
  { body: "Open a fixed deposit account at your bank for money you won't need for 6+ months. Rates are better.", category: "saving" },
  { body: "Track every shilling you save in MyTereka — seeing the number grow is motivating.", category: "saving" },
  { body: "If you share a home, split bills equally and each person saves their share of what would have been spent.", category: "saving" },
  { body: "Savings grow fastest when you treat them like a non-negotiable expense, not an afterthought.", category: "saving" },

  // budgeting
  { body: "Buying from Nakasero or Owino market instead of supermarkets saves up to 40% on groceries.", category: "budgeting" },
  { body: "Plan your meals for the week before shopping. You'll buy less, waste less, and spend less.", category: "budgeting" },
  { body: "Cook matooke, beans, and groundnut stew in bulk on Sundays — saves both time and money during the week.", category: "budgeting" },
  { body: "Set a weekly food budget in MyTereka and track every market purchase against it.", category: "budgeting" },
  { body: "Internet bundles bought monthly cost less per GB than daily bundles. Plan ahead.", category: "budgeting" },
  { body: "Boda fares add up. Walk routes under 1km — it's cheaper and better for your health.", category: "budgeting" },
  { body: "Use the 50/30/20 rule: 50% needs, 30% wants, 20% savings. Adjust for Ugandan realities.", category: "budgeting" },
  { body: "Log every transaction in MyTereka immediately — guessing later leads to budget overruns.", category: "budgeting" },
  { body: "Before buying anything, ask: is this a need or a want? Pause for 30 seconds.", category: "budgeting" },
  { body: "Airtime: buy weekly bundles instead of topping up daily — you spend less overall.", category: "budgeting" },
  { body: "School fees come every term. Start saving for next term the day you pay this term.", category: "budgeting" },
  { body: "Review last month's spending in MyTereka Analytics — one surprising category will reveal itself.", category: "budgeting" },
  { body: "Eating out once a week costs what home cooking costs in 5 days. Limit restaurant meals.", category: "budgeting" },
  { body: "Carry only the cash you need for the day. Leaving your card home reduces impulse spending.", category: "budgeting" },
  { body: "Entertainment budget: decide a fixed amount per month. When it's gone, it's gone.", category: "budgeting" },
  { body: "Track taxi and boda fares for one week. You might be surprised how much transport costs.", category: "budgeting" },
  { body: "Cancel subscriptions you haven't used this month. DStv, Netflix, gym — audit them all.", category: "budgeting" },
  { body: "Buy clothing at end-of-season sales. Prices drop 30–50% and quality doesn't change.", category: "budgeting" },
  { body: "Use a shopping list and stick to it. Supermarkets are designed to make you spend more.", category: "budgeting" },
  { body: "Cook tea and pack lunch from home. Buying tea daily at work can cost UGX 30,000+ per month.", category: "budgeting" },
  { body: "Review your phone data usage. Most people pay for plans larger than what they actually need.", category: "budgeting" },
  { body: "Budget for irregular expenses: car service, medical, school items. Divide annual cost by 12.", category: "budgeting" },
  { body: "Whenever you go over budget in a category, investigate why — not to punish, but to learn.", category: "budgeting" },

  // mobile_money
  { body: "MTN MoMo float: keep small operational cash on mobile money, larger savings elsewhere.", category: "mobile_money" },
  { body: "Always verify recipient numbers before sending mobile money. Mistakes are hard to reverse.", category: "mobile_money" },
  { body: "MTN MoMo and Airtel Money charge withdrawal fees. Reduce trips to the agent — batch withdrawals.", category: "mobile_money" },
  { body: "Send money between mobile networks using bank transfers to avoid high cross-network fees.", category: "mobile_money" },
  { body: "Check mobile money transaction limits. Large transfers may require multiple transactions with fees on each.", category: "mobile_money" },
  { body: "Mobile money is convenient but not a savings account. Don't keep all your money on it.", category: "mobile_money" },
  { body: "MTN MoMo agents charge different fees. Shop around in your area for lower withdrawal rates.", category: "mobile_money" },
  { body: "Use mobile money payment instead of cash for utilities — faster and traceable.", category: "mobile_money" },
  { body: "Never share your mobile money PIN. Airtel and MTN will never call asking for your PIN.", category: "mobile_money" },
  { body: "Register for Airtel Money or MTN MoMo merchant account if you run a business — lower fees.", category: "mobile_money" },
  { body: "Set up auto-save through MTN MoMo if available in your plan — automatic saving beats manual every time.", category: "mobile_money" },

  // investing
  { body: "SACCOs in Uganda pay annual dividends of 8–15% — far better than leaving money idle on MoMo.", category: "investing" },
  { body: "Ugandan Treasury Bills offer government-backed returns. Check Bank of Uganda for current rates.", category: "investing" },
  { body: "Invest in skills: a short course that increases your income is the best ROI you can get.", category: "investing" },
  { body: "Don't invest money you'll need in the next 6 months. Keep that in liquid savings.", category: "investing" },
  { body: "Start with what you have. Investing UGX 10,000/month is better than waiting for UGX 1,000,000.", category: "investing" },
  { body: "Diversify: don't put everything in one SACCO, one stock, or one business.", category: "investing" },
  { body: "Beware of get-rich-quick schemes promising 50%+ returns. If it sounds too good, it's a scam.", category: "investing" },
  { body: "Business investment: calculate your break-even point before starting. Know when you'll profit.", category: "investing" },
  { body: "Agricultural investment: land near Kampala appreciates. But it requires patience — 5+ year horizon.", category: "investing" },
  { body: "Unit trusts on the Uganda Securities Exchange allow investing in diversified funds with small amounts.", category: "investing" },
  { body: "Reinvest profits from your business for at least 2 years before increasing personal withdrawals.", category: "investing" },
  { body: "Your network is your net worth. Relationships with trustworthy business people create opportunities.", category: "investing" },

  // mindset
  { body: "Financial stress is normal. The fact that you're tracking money means you're already ahead of most.", category: "mindset" },
  { body: "Compare your finances to your past self, not to others. Everyone's journey is different.", category: "mindset" },
  { body: "A missed savings day is not a failure — just resume the next day. Streaks reset; discipline doesn't.", category: "mindset" },
  { body: "Money is a tool. The goal isn't to accumulate it — it's to use it to build the life you want.", category: "mindset" },
  { body: "Talk about money with your spouse or partner. Financial secrecy destroys households.", category: "mindset" },
  { body: "Teach your children about money early. Let them save part of any pocket money they receive.", category: "mindset" },
  { body: "Don't lend money you can't afford to lose. Treat loans to friends and family as gifts mentally.", category: "mindset" },
  { body: "Celebrate small financial wins. Hitting a savings milestone deserves recognition.", category: "mindset" },
  { body: "Avoid financial FOMO. Someone else's phone upgrade or holiday shouldn't derail your plan.", category: "mindset" },
  { body: "The best financial plan is one you can actually follow. Don't build a budget too strict to sustain.", category: "mindset" },
  { body: "Give generously within your means. Generosity creates community, and community creates resilience.", category: "mindset" },
  { body: "If you earn more, save more — not just spend more. Lifestyle inflation is the silent budget killer.", category: "mindset" },
  { body: "Financial goals without a timeline are just wishes. Set a date for every goal in MyTereka.", category: "mindset" },

  // income
  { body: "Diversify income streams. If your main income stopped tomorrow, would you survive 3 months?", category: "income" },
  { body: "Freelance skills (design, coding, writing, tutoring) can earn extra income on weekends.", category: "income" },
  { body: "Upwork and online platforms pay in USD — at today's rates, even $50/month is significant in UGX.", category: "income" },
  { body: "Your salary is not your only option. Identify one skill you can monetize outside of work.", category: "income" },
  { body: "Track all income sources in MyTereka — even small amounts from side work.", category: "income" },
  { body: "Negotiate your salary at review time. Silence costs you money every month.", category: "income" },
  { body: "Agribusiness: growing tomatoes, onions, or maize seasonally can generate meaningful income with low capital.", category: "income" },
  { body: "Renting out a room, a vehicle, or equipment you own is passive income. List what you have.", category: "income" },
  { body: "Every skill can be taught. If you know Excel, Photoshop, or cooking, you can charge for lessons.", category: "income" },
  { body: "Identify one recurring expense you can turn into a business — e.g. pay rent vs. build and charge others.", category: "income" },

  // debt
  { body: "Pay off high-interest debt before saving for anything else. Interest is the enemy of savings.", category: "debt" },
  { body: "If you have mobile money loans (MoMo loan, Airtel Mambo), pay them off at month-end — interest is steep.", category: "debt" },
  { body: "Don't borrow for consumption (food, clothes, entertainment). Only borrow for income-generating assets.", category: "debt" },
  { body: "Microfinance interest rates in Uganda can exceed 30% annually. Read the fine print before borrowing.", category: "debt" },
  { body: "Clear one debt fully before starting a new one. Focus beats spreading thin payments.", category: "debt" },
  { body: "If you're in debt, pause non-essential savings goals and redirect to debt repayment first.", category: "debt" },
  { body: "Credit is not free money. Every UGX borrowed today costs more UGX tomorrow.", category: "debt" },

  // school_fees
  { body: "Schools release fee balances every term. Budget for them in January, May, and September.", category: "school_fees" },
  { body: "Start saving for next term's school fees on the first day you pay this term's fees.", category: "school_fees" },
  { body: "School requirements lists come late. Budget UGX 20,000–50,000 above stated fees for extras.", category: "school_fees" },
  { body: "Some schools offer discounts for early or full fee payment. Ask your school about this.", category: "school_fees" },
  { body: "University application and enrollment fees add up — save specifically for these, separate from tuition.", category: "school_fees" },
  { body: "Government bursary programs exist for top-performing students. Investigate NCHE and government schemes.", category: "school_fees" },

  // health
  { body: "Budget for medical costs. Even if you're healthy, set aside UGX 20,000/month for emergencies.", category: "health" },
  { body: "NHIF health schemes can reduce out-of-pocket hospital costs. Ask your employer if enrolled.", category: "health" },
  { body: "Preventive health (clean water, mosquito nets, fruit, vegetables) is cheaper than hospital treatment.", category: "health" },
  { body: "Generic medicines at government health centers cost far less than branded drugs at private clinics.", category: "health" },
  { body: "Mental health matters. Financial stress is one of the biggest causes of poor health — address both.", category: "health" },

  // goals
  { body: "A goal without a number is just a wish. Set the exact amount you want to save, and by when.", category: "goals" },
  { body: "Break big goals into milestones. Celebrate when you hit 25%, 50%, and 75% — not just 100%.", category: "goals" },
  { body: "Shared savings goals with family or friends create accountability and reduce temptation to quit.", category: "goals" },
  { body: "When you miss a savings deposit, don't skip the next one — make it up plus the usual amount.", category: "goals" },
  { body: "Your goals will change. Review them every 3 months and adjust — that's wisdom, not failure.", category: "goals" },
  { body: "Completing a savings goal, no matter how small, builds the muscle memory for larger ones.", category: "goals" },
  { body: "Visualize what completing your goal looks like — the house, the graduation, the trip. Keep that in mind.", category: "goals" },
  { body: "Auto-debit to your goal account on payday. What you don't see, you don't spend.", category: "goals" },

  // general_ug
  { body: "End-month prices in Kampala rise. Do grocery shopping in the middle of the month to spend less.", category: "general_ug" },
  { body: "Bodaboda is convenient but expensive for daily commutes. Matatus cost 2–5x less per trip.", category: "general_ug" },
  { body: "Power outages increase generator fuel costs. Invest in energy-saving bulbs and charge devices during grid hours.", category: "general_ug" },
  { body: "Seasonal price drops: buy in bulk during harvest season (beans, maize, groundnuts) and store.", category: "general_ug" },
  { body: "Foreign exchange moves. If you earn in UGX but have USD costs, track the rate monthly.", category: "general_ug" },
  { body: "During Ramadan and holidays, markets get expensive. Stock essentials a week before.", category: "general_ug" },
  { body: "Water jerry cans: if you buy water, track the monthly cost — it's often more than people think.", category: "general_ug" },
  { body: "Charcoal prices spike in dry season. Buy and store a bag or two when prices are low.", category: "general_ug" },
  { body: "Many Ugandan banks charge monthly account maintenance fees. Check your statement and switch if needed.", category: "general_ug" },
  { body: "Property in peri-urban areas (Wakiso, Mukono, Jinja) is cheaper than Kampala and appreciating fast.", category: "general_ug" },
  { body: "Reinvesting profits in your own business before paying yourself is how small businesses survive year one.", category: "general_ug" },
  { body: "Wedding contributions (kwanjula, introduction): budget for these as a social obligation expense, not a surprise.", category: "general_ug" },
  { body: "Church tithe and giving: if you practice this, budget it explicitly — don't let it disrupt your savings plan.", category: "general_ug" },
  { body: "Funeral contributions happen unexpectedly. Keep UGX 20,000–50,000 reserved for this social obligation.", category: "general_ug" },
  { body: "Tax on MoMo withdrawals (0.5% levy) adds up. Factor it into your cash-out calculations.", category: "general_ug" },
]
